markdown: kramdown

title: Ants, Genomes & Evolution @ Queen Mary University London

url: '//wurmlab.github.io'
production_url: 'https://wurmlab.github.io'

permalink: "/news/:year-:month-:day-:title/"

author:
    name: Yannick Wurm Laboratory
    email: y.wurm@qmul.ac.uk
    github: wurmlab
    twitter: yannick__

#comments:
#    provider: disqusasdf
#    disqus: yannickwurm
#        short_name: "yannickwurm"
#    disqus_name: "adsf"

analytics:
    provider: google 
    google: 
        tracking_id: 'UA-471841-2'
        domain: 'wurmlab.github.io'

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'Rakefile']

gems:
  - jekyll-redirect-from
